### ISSUE TITLE
Any plan to update this guide to use D3 v4?

### ISSUE THREAD

**Issue by kanitw** [vlandham/js_data#35]
HI @vlandham and Bocoup team,

I hope all is well. 

We're considering to use your JS Data guide as a reading material for our undergraduate Data Visualization class at UW next quarter.  (We love it!)

Meanwhile, we plan to use D3 v4 as the primary visualization toolkit in our class.  
Thus, we wonder if you have any plan for updating this guide to use D3 v4?
(It would make it way easier for our students if all reading materials 
use a consistent version of D3.) 

If you'd like, we are happy to help update this to D3 v4 too.  
That said, I wonder if you still want to make the guide backward compatible for users who use D3 v3 and older.  If so, do you have any preferred method to maintain this backward compatibility? 
One simple way would be just to add note that some methods had a different name prior to v4.

Please let us know  

Thanks!
–Ham

cc: @jheer, @jhoffswell 

## TODO list to update

(I'll keep adding relevant TODO list here as I read through the whole guide.)

- [x] http://learnjsdata.com/read_data.html: Update link to d3-request
- [x] Link to d3.nest in http://learnjsdata.com/group_data.html it outdated. It's actually now in d3-collection.
- [x] http://learnjsdata.com/time.html, `d3.time.format` is now `d3.timeFormat`
- [x] http://learnjsdata.com/node.html: `d3.csv.format` => `d3.csvFormat`

**Comment by vlandham** [comment]
Hi Ham!

Very good to hear from you!

I'd very much like to update this guide to be D3v4 compatible. Its been on my todo list for some time now. 

Let me dive into the current deployment process we have for this site (its been awhile since i looked at it). But i could envision saving the current state of the guide in a `/v3` sub-folder (linked to from the main page) and then keeping the current version to be straight d3v4. 

Combining them in the same document, as you indicated, would be another option. 

Thanks for offering to help. Just the todo here is a great starting point for me! perhaps we could collaborate on reviewing modifications / additions. 

Thanks for the heads up! As a next step, I will look at archiving the current state in a v3 directory.

**Comment by vlandham** [comment]
on further reflection - i think there are some benefits to the the methodology you suggest. having both d3v3 and v4 instructions on the same page _could_ be beneficial to people trying to integrate old code with new code... but we would want to make it not confusing to the folks wanting just v4 instructions. 

will continue to reflect. Thanks for updating the TODO list!

**Comment by grssnbchr** [comment]
~~Do you guys think http://learnjsdata.com/combine_data.html must be updated too? It uses D3 in one snippet, but only `d3.merge` and `queue`. I haven't worked with D3 for ages so I don't really know what's knew. Would be happy to dig into and update it though if it's necessary.~~
Lol I just realized @vlandham already updated it... sorry ;-) And thanks!

**Comment by vlandham** [comment]
ha. i was just going to say, i've started down the path:

https://github.com/vlandham/js_data/compare/update-d3v4?expand=1

should have it able to be merged in a day or so. But you are right. there are more changes to be done!

**Comment by vlandham** [comment]
@kanitw I've merged @1wheel and my changes to master and redeployed to http://learnjsdata.com/

do you want to do a pass through to ensure the guide is sufficiently converted to d3v4 - for your purposes? 

Thanks again for the push.
